-- MySQL Script generated by MySQL Workbench
-- Tue Apr 10 01:21:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema booknow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema booknow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `booknow` DEFAULT CHARACTER SET utf8 ;
USE `booknow` ;

-- -----------------------------------------------------
-- Table `booknow`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booknow`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(50) NULL,
  `email` VARCHAR(70) NULL,
  `cidade` VARCHAR(55) NULL,
  `estado` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `endereco` VARCHAR(70) NULL,
  `complemento` VARCHAR(50) NULL,
  `senha` VARCHAR(50) NULL,
  `foto` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booknow`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booknow`.`postagem` (
  `idpostagem` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `genero` VARCHAR(50) NOT NULL,
  `EstadoLivro` VARCHAR(45) NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idpostagem`),
  INDEX `fk_postagem_usuarios1_idx` (`usuarios_idusuarios` ASC),
  CONSTRAINT `fk_postagem_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `booknow`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booknow`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booknow`.`comentario` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `postagem_idpostagem` INT NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idcomentario`, `postagem_idpostagem`),
  INDEX `fk_comentario_postagem_idx` (`postagem_idpostagem` ASC),
  INDEX `fk_comentario_usuarios1_idx` (`usuarios_idusuarios` ASC),
  CONSTRAINT `fk_comentario_postagem`
    FOREIGN KEY (`postagem_idpostagem`)
    REFERENCES `booknow`.`postagem` (`idpostagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `booknow`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booknow`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booknow`.`avaliacao` (
  `idavaliacao` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NULL,
  `usuarios_idusuarios` INT NOT NULL,
  `comentario_idcomentario` INT NOT NULL,
  `comentario_postagem_idpostagem` INT NOT NULL,
  PRIMARY KEY (`idavaliacao`),
  INDEX `fk_avaliacao_usuarios1_idx` (`usuarios_idusuarios` ASC),
  INDEX `fk_avaliacao_comentario1_idx` (`comentario_idcomentario` ASC, `comentario_postagem_idpostagem` ASC),
  CONSTRAINT `fk_avaliacao_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `booknow`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_comentario1`
    FOREIGN KEY (`comentario_idcomentario` , `comentario_postagem_idpostagem`)
    REFERENCES `booknow`.`comentario` (`idcomentario` , `postagem_idpostagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
